# Site settings
title: "Volt Documentation"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.volt-lang.org" # the base hostname & protocol for your site
twitter_username:
github_username: VoltLang
